name: Arduino Compile

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install AVR core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile
        run: arduino-cli compile --fqbn arduino:avr:leonardo .
